receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  debug:
    verbosity: detailed
  prometheus:
    # endpoint: 0.0.0.0:55681
    endpoint: "0.0.0.0:8889"
  otlp:
    endpoint: tempo:4007
    tls:
      insecure: true


extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]